from models.deeplab import *
from models.setr import *
from models.glavitu import *
from models.mbcnn import *
from models.fcn import *
from models.resunet import *
from models.unet import *
from models.utils import *
from models.fgnet import *